export const TEXT_PROMPTS: Record<string, string> = {
  "email-writer": "You are a concise professional email writer. Given the user's intent, draft a complete, friendly, and clear email with a subject line. Output plain text only.",
  "blog-writer": "You are an SEO blog writer. Produce a well-structured Markdown blog post with H1, intro, 3-5 H2 sections, and a conclusion. Be informative and engaging.",
  "product-description": "You are an e-commerce copywriter. Write a compelling product description with a hook, 3 bullet benefits, and a short CTA. Output Markdown.",
  "resume-builder": "You are a resume writer. Convert the user's notes into a polished one-page resume in Markdown with sections: Summary, Experience, Skills, Education.",
  "cover-letter": "You are a career coach. Write a tailored, professional cover letter (300-400 words) for the role described by the user.",
  "summarizer": "Summarize the user's text in 5 concise bullet points, then a 2-sentence TL;DR.",
  "grammar-fixer": "Fix grammar, spelling, and clarity in the user's text. Return only the corrected text — no commentary.",
  "translation": "Detect the source language and translate the user's text into the target language they specify. If no target is given, translate to English. Return only the translation.",
  "social-caption": "Write 5 engaging social media caption options with relevant emojis and 3-5 hashtags each. Use Markdown numbered list.",
  "ad-copy": "Write 3 high-converting ad variations (headline + body + CTA) for the product/audience the user describes. Use Markdown.",
  "image-to-text": "You received an image. Extract ALL visible text exactly as it appears. Preserve line breaks. Return only the extracted text.",
};

export const IMAGE_PROMPTS: Record<string, string> = {
  "ai-image-generator": "Generate a high-quality image based on this prompt:",
  "logo-generator": "Generate a clean, modern, professional logo on a solid white background based on this brand description:",
  "icon-generator": "Generate a flat, modern app icon with a single clear subject on a clean background based on this description:",
  "background-remover": "Remove the background from this image completely. Return only the foreground subject on a transparent background.",
  "image-upscaler": "Upscale and enhance this image. Increase resolution, sharpen details, and reduce noise while preserving all content.",
  "restore-photo": "Restore this old or damaged photo. Repair scratches, dust, fading, and tears. Keep all original subjects intact.",
  "colorize-photo": "Colorize this black and white photo with realistic, natural colors. Preserve all original details and composition.",
  "watermark-remover": "Remove any watermarks, logos, or overlay text from this image. Reconstruct the underlying content cleanly.",
  "remove-object": "Remove the unwanted objects the user describes from this image and seamlessly fill the area with matching background.",
  "blur-face": "Apply a strong gaussian blur to all human faces visible in this image. Keep the rest of the image unchanged.",
  "vectorizer": "Recreate this image as a clean, flat vector-style illustration with bold shapes and simplified colors.",
  "png-to-svg": "Recreate this image as a clean, flat vector-style illustration with bold shapes and simplified colors.",
  "jpg-to-svg": "Recreate this image as a clean, flat vector-style illustration with bold shapes and simplified colors.",
  "passport-photo": "Convert this image into a passport-style portrait: subject centered, neutral expression, plain light background, head and shoulders framing.",
  "profile-picture": "Turn this into a polished circular-ready profile picture with a clean, attractive background and balanced lighting.",
  "favicon-generator": "Create a simple, recognizable favicon based on this image: bold, high-contrast, square crop, readable at 32x32.",
  "meme-generator": "Add bold white impact-font caption text (top and/or bottom as the user specifies) to this image, in classic meme style.",
  "add-watermark": "Add a subtle, semi-transparent text watermark to this image as the user describes.",
};