import { useRef, useState, type DragEvent } from "react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Upload, Download, Loader2, FileCheck2, X, Copy, Check } from "lucide-react";
import { toast } from "sonner";
import type { Tool } from "@/lib/tools";

type Status = "idle" | "processing" | "done";

interface MockResult {
  blob: Blob;
  filename: string;
  url: string;
  previewUrl?: string; // for images
  previewText?: string; // for text/code outputs
  kind: "image" | "pdf" | "text" | "binary";
}

function makeMinimalPdf(title: string, body: string): Blob {
  // Minimal hand-crafted single-page PDF
  const esc = (s: string) => s.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
  const stream = `BT /F1 22 Tf 60 760 Td (${esc(title)}) Tj ET\nBT /F1 12 Tf 60 720 Td (${esc(body)}) Tj ET\nBT /F1 10 Tf 60 690 Td (Generated by FoqusTools - demo output) Tj ET`;
  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>",
    `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`,
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
  ];
  let pdf = "%PDF-1.4\n";
  const offsets: number[] = [];
  objects.forEach((o, i) => {
    offsets.push(pdf.length);
    pdf += `${i + 1} 0 obj\n${o}\nendobj\n`;
  });
  const xref = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  offsets.forEach((o) => { pdf += `${String(o).padStart(10, "0")} 00000 n \n`; });
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;
  return new Blob([pdf], { type: "application/pdf" });
}

async function makeMockImage(toolName: string, sourceName?: string): Promise<{ blob: Blob; url: string }> {
  const canvas = document.createElement("canvas");
  canvas.width = 1024; canvas.height = 640;
  const ctx = canvas.getContext("2d")!;
  const g = ctx.createLinearGradient(0, 0, 1024, 640);
  g.addColorStop(0, "#7c3aed");
  g.addColorStop(1, "#ec4899");
  ctx.fillStyle = g;
  ctx.fillRect(0, 0, 1024, 640);
  ctx.fillStyle = "rgba(255,255,255,0.08)";
  for (let i = 0; i < 30; i++) ctx.fillRect(Math.random() * 1024, Math.random() * 640, 80, 80);
  ctx.fillStyle = "white";
  ctx.font = "bold 56px system-ui, -apple-system, sans-serif";
  ctx.fillText("FoqusTools", 60, 120);
  ctx.font = "32px system-ui, sans-serif";
  ctx.fillText(toolName, 60, 180);
  ctx.font = "20px system-ui, sans-serif";
  ctx.fillText(`Demo output${sourceName ? ` for ${sourceName}` : ""}`, 60, 230);
  ctx.font = "16px system-ui, sans-serif";
  ctx.fillText("Connect a backend to deliver real processed images.", 60, 580);
  const blob: Blob = await new Promise((res) => canvas.toBlob((b) => res(b!), "image/png"));
  return { blob, url: URL.createObjectURL(blob) };
}

async function buildMockResult(tool: Tool, files: File[], text: string): Promise<MockResult> {
  const stamp = new Date().toISOString().replace(/[:.]/g, "-");
  const baseName = (files[0]?.name.replace(/\.[^.]+$/, "") || tool.slug);

  if (tool.inputType === "image" || tool.slug.includes("image")) {
    const { blob, url } = await makeMockImage(tool.name, files[0]?.name);
    return { blob, url, previewUrl: url, filename: `${baseName}-${tool.slug}.png`, kind: "image" };
  }
  if (tool.inputType === "pdf" || tool.slug.includes("pdf")) {
    const blob = makeMinimalPdf(tool.name, `Demo output${files[0] ? ` for ${files[0].name}` : ""}`);
    return { blob, url: URL.createObjectURL(blob), filename: `${baseName}-${tool.slug}.pdf`, kind: "pdf" };
  }
  if (tool.inputType === "text") {
    const out = `# ${tool.name}\n\nGenerated: ${stamp}\n\n## Input\n${text || "(empty)"}\n\n## Demo Output\nThis is a placeholder result produced by FoqusTools.\nConnect a backend to deliver real AI-generated content.\n`;
    const blob = new Blob([out], { type: "text/markdown" });
    return { blob, url: URL.createObjectURL(blob), previewText: out, filename: `${tool.slug}-${stamp}.md`, kind: "text" };
  }
  // file/none
  const out = `FoqusTools demo output\nTool: ${tool.name}\nGenerated: ${stamp}\nFiles: ${files.map((f) => f.name).join(", ") || "(none)"}\n`;
  const blob = new Blob([out], { type: "text/plain" });
  return { blob, url: URL.createObjectURL(blob), previewText: out, filename: `${tool.slug}-${stamp}.txt`, kind: "text" };
}

export function MockToolRunner({ tool }: { tool: Tool }) {
  const [files, setFiles] = useState<File[]>([]);
  const [text, setText] = useState("");
  const [status, setStatus] = useState<Status>("idle");
  const [result, setResult] = useState<MockResult | null>(null);
  const [copied, setCopied] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);

  const isFileBased = tool.inputType !== "text" && tool.inputType !== "none";
  const cta = tool.cta ?? (tool.inputType === "text" ? "Generate" : "Process File");

  function onDrop(e: DragEvent) {
    e.preventDefault();
    if (e.dataTransfer.files?.length) setFiles(Array.from(e.dataTransfer.files));
  }

  async function run() {
    if (result) URL.revokeObjectURL(result.url);
    setResult(null);
    setStatus("processing");
    await new Promise((r) => setTimeout(r, 1400));
    const r = await buildMockResult(tool, files, text);
    setResult(r);
    setStatus("done");
  }

  function download() {
    if (!result) return;
    const a = document.createElement("a");
    a.href = result.url;
    a.download = result.filename;
    document.body.appendChild(a);
    a.click();
    a.remove();
    toast.success("Download started", {
      description: `${result.filename} (${(result.blob.size / 1024).toFixed(1)} KB) saved to your device.`,
    });
  }

  async function copyOutput() {
    if (!result?.previewText) return;
    try {
      await navigator.clipboard.writeText(result.previewText);
      setCopied(true);
      setTimeout(() => setCopied(false), 1800);
    } catch {
      // ignore — clipboard may be blocked
    }
  }

  const canRun = isFileBased ? files.length > 0 : tool.inputType === "none" ? true : text.trim().length > 0;

  return (
    <div className="space-y-5">
      {isFileBased && (
        <div
          onDragOver={(e) => e.preventDefault()}
          onDrop={onDrop}
          onClick={() => inputRef.current?.click()}
          className="cursor-pointer rounded-2xl border-2 border-dashed border-border hover:border-primary/60 hover:bg-accent/30 transition-colors p-10 text-center"
        >
          <div className="mx-auto w-12 h-12 rounded-xl bg-[image:var(--gradient-brand)] grid place-items-center mb-3 shadow-[var(--shadow-soft)]">
            <Upload className="w-5 h-5 text-white" />
          </div>
          <p className="font-medium">Drop your {tool.inputType === "image" ? "image" : tool.inputType === "pdf" ? "PDF" : "file"} here</p>
          <p className="text-sm text-muted-foreground mt-1">or click to browse — max 50MB</p>
          <input ref={inputRef} type="file" accept={tool.accept} multiple className="hidden" onChange={(e) => setFiles(Array.from(e.target.files ?? []))} />
        </div>
      )}

      {isFileBased && files.length > 0 && (
        <ul className="space-y-2">
          {files.map((f, i) => (
            <li key={i} className="flex items-center justify-between gap-3 p-3 rounded-md border bg-muted/40 text-sm">
              <div className="flex items-center gap-2 truncate"><FileCheck2 className="w-4 h-4 text-primary shrink-0" /><span className="truncate">{f.name}</span><span className="text-muted-foreground text-xs">{(f.size / 1024).toFixed(1)} KB</span></div>
              <button onClick={() => setFiles((arr) => arr.filter((_, j) => j !== i))} className="text-muted-foreground hover:text-foreground p-1"><X className="w-4 h-4" /></button>
            </li>
          ))}
        </ul>
      )}

      {tool.inputType === "text" && (
        <Textarea value={text} onChange={(e) => setText(e.target.value)} placeholder="Type or paste your input here…" className="min-h-40" />
      )}

      <div className="rounded-xl border bg-muted/30 p-4">
        <h3 className="text-sm font-semibold mb-2">Settings</h3>
        <p className="text-xs text-muted-foreground">Tool-specific options will appear here. Connect a backend to unlock full configuration.</p>
      </div>

      <div className="flex flex-wrap gap-2">
        <Button onClick={run} disabled={!canRun || status === "processing"} className="bg-[image:var(--gradient-brand)] text-primary-foreground hover:opacity-90 shadow-[var(--shadow-soft)]">
          {status === "processing" ? (<><Loader2 className="w-4 h-4 animate-spin" /> Processing…</>) : cta}
        </Button>
        <Button variant="outline" disabled={status !== "done" || !result} onClick={download}>
          <Download className="w-4 h-4" /> Download{result ? ` ${result.filename.split(".").pop()?.toUpperCase()}` : ""}
        </Button>
        {result?.kind === "text" && (
          <Button variant="outline" onClick={copyOutput} disabled={!result.previewText}>
            {copied ? (<><Check className="w-4 h-4 text-primary" /> Copied</>) : (<><Copy className="w-4 h-4" /> Copy output</>)}
          </Button>
        )}
      </div>

      <div className="rounded-xl border bg-card p-5 min-h-32">
        <h3 className="text-sm font-semibold mb-2">Result preview</h3>
        {status === "idle" && <p className="text-sm text-muted-foreground">Your output will appear here once processing is complete.</p>}
        {status === "processing" && <div className="flex items-center gap-2 text-sm text-muted-foreground"><Loader2 className="w-4 h-4 animate-spin" /> Working on it…</div>}
        {status === "done" && result && (
          <div className="space-y-3">
            {result.previewUrl && <img src={result.previewUrl} alt="Preview" className="max-h-72 rounded-lg border" />}
            {result.previewText && <pre className="text-xs font-mono p-3 rounded-md border bg-muted/40 whitespace-pre-wrap max-h-72 overflow-auto">{result.previewText}</pre>}
            {result.kind === "pdf" && <embed src={result.url} type="application/pdf" className="w-full h-72 rounded-md border" />}
            <p className="text-xs text-muted-foreground">Demo file ready: <span className="font-mono">{result.filename}</span> — {(result.blob.size / 1024).toFixed(1)} KB</p>
          </div>
        )}
      </div>
    </div>
  );
}