/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolSlugRouteImport } from './routes/tool.$slug'
import { Route as ApiAiTextRouteImport } from './routes/api/ai/text'
import { Route as ApiAiImageRouteImport } from './routes/api/ai/image'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolSlugRoute = ToolSlugRouteImport.update({
  id: '/tool/$slug',
  path: '/tool/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiTextRoute = ApiAiTextRouteImport.update({
  id: '/api/ai/text',
  path: '/api/ai/text',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiImageRoute = ApiAiImageRouteImport.update({
  id: '/api/ai/image',
  path: '/api/ai/image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tools': typeof ToolsRoute
  '/tool/$slug': typeof ToolSlugRoute
  '/api/ai/image': typeof ApiAiImageRoute
  '/api/ai/text': typeof ApiAiTextRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tools': typeof ToolsRoute
  '/tool/$slug': typeof ToolSlugRoute
  '/api/ai/image': typeof ApiAiImageRoute
  '/api/ai/text': typeof ApiAiTextRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tools': typeof ToolsRoute
  '/tool/$slug': typeof ToolSlugRoute
  '/api/ai/image': typeof ApiAiImageRoute
  '/api/ai/text': typeof ApiAiTextRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/tools'
    | '/tool/$slug'
    | '/api/ai/image'
    | '/api/ai/text'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/tools'
    | '/tool/$slug'
    | '/api/ai/image'
    | '/api/ai/text'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/tools'
    | '/tool/$slug'
    | '/api/ai/image'
    | '/api/ai/text'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ToolsRoute: typeof ToolsRoute
  ToolSlugRoute: typeof ToolSlugRoute
  ApiAiImageRoute: typeof ApiAiImageRoute
  ApiAiTextRoute: typeof ApiAiTextRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool/$slug': {
      id: '/tool/$slug'
      path: '/tool/$slug'
      fullPath: '/tool/$slug'
      preLoaderRoute: typeof ToolSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/text': {
      id: '/api/ai/text'
      path: '/api/ai/text'
      fullPath: '/api/ai/text'
      preLoaderRoute: typeof ApiAiTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/image': {
      id: '/api/ai/image'
      path: '/api/ai/image'
      fullPath: '/api/ai/image'
      preLoaderRoute: typeof ApiAiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ToolsRoute: ToolsRoute,
  ToolSlugRoute: ToolSlugRoute,
  ApiAiImageRoute: ApiAiImageRoute,
  ApiAiTextRoute: ApiAiTextRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
